name: Download FX Rates Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Daily at 1 AM UTC

permissions:
  contents: write
  actions: write

jobs:
  split-fxpairs:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.ref == 'refs/heads/main')
    outputs:
      matrix: ${{ steps.split.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r fxrates/requirements.txt

      - name: Install jq
        run: |
          sudo apt-get install jq

      - name: Generate Matrix Chunks
        id: split
        env:
          CHUNK_SIZE: ${{ secrets.CHUNK_SIZE_FX }}
        run: |
          CHUNK_SIZE=${CHUNK_SIZE:-6}
          echo "🔢 Using CHUNK_SIZE=$CHUNK_SIZE"
          MATRIX=$(python fxrates/splitter.py --input fxrates/fxpairs.json --chunk-size "$CHUNK_SIZE" | jq -c .)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  run-fetch:
    needs: split-fxpairs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.split-fxpairs.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r fxrates/requirements.txt

      - name: Run Export
        run: |
          FXPAIRS_JSON='${{ toJson(matrix.chunk) }}'
          python fxrates/export.py --fxpairs "$FXPAIRS_JSON"

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: fxrate-${{ github.job }}-${{ strategy.job-index }}
          path: output/*.json

  collect-and-push:
    needs: run-fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Push Stocks JSONs to Target Repo
        if: success()
        env:
          TARGET_REPO_MAIN: ${{ secrets.TARGET_REPO }}
          TARGET_BRANCH_MAIN: ${{ secrets.TARGET_BRANCH }}
          TARGET_REPO_TEST: ${{ secrets.TARGET_REPO_TEST }}
          TARGET_BRANCH_TEST: ${{ secrets.TARGET_BRANCH_TEST }}
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          echo "🔍 Branch is $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            TARGET_REPO="$TARGET_REPO_MAIN"
            BRANCH="$TARGET_BRANCH_MAIN"
          elif [[ "$GITHUB_REF" == "refs/heads/test" ]]; then
            TARGET_REPO="$TARGET_REPO_TEST"
            BRANCH="$TARGET_BRANCH_TEST"
          else
            echo "🚫 Workflow not triggered on 'main' or 'test' branch. Exiting..."
            exit 0
          fi
          
          WORKDIR=$(mktemp -d)
          
          echo "📦 Cloning target repo..."
          git clone --depth 1 --branch $BRANCH https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@$TARGET_REPO $WORKDIR
          
          echo "📂 Creating docs/fxrates folder if missing..."
          mkdir -p $WORKDIR/docs/fxrates

          echo "📂 Copying output files..."
          cp -f artifacts/**/*.json $WORKDIR/docs/fxrates/

          cd $WORKDIR
          if git status --porcelain | grep .; then
            git add docs/fxrates/*.json
            git commit -m "📈 Update JSONs in docs/fxrates/ from ${{ github.repository }} at ${{ github.run_id }}"
            git push origin $BRANCH
            echo "✅ JSONs pushed to $TARGET_REPO docs/fxrates/"
          else
            echo "ℹ️ No changes to commit."
          fi