name: Download all.json (Tickers Dropdown)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 6'  # Every Saturday at 12:30 AM UTC

jobs:
  split-stocks:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.ref == 'refs/heads/main')
    outputs:
      matrix: ${{ steps.split.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate Matrix Chunks
        id: gen_matrix
        env:
          CHUNK_SIZE: ${{ secrets.CHUNK_SIZE_TICKERS }}
        run: |
          CHUNK_SIZE=$CHUNK_SIZE
          echo "🔢 Using CHUNK_SIZE=$CHUNK_SIZE"
          MATRIX=$(python stocks/split_stocks.py stocks/stocks.json "$CHUNK_SIZE")
          echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MATRIX" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Generated Matrix
        run: |
          echo "🔁 Generated matrix"
          echo '${{ toJson(steps.gen_matrix.outputs.matrix) }}'

  run-fetch:
    needs: split-stocks
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.split-stocks.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r stocks/requirements.txt

      - name: Run Export
        run: |
          python stocks/export_all_stocks.py --tickers "${{ join(matrix.chunk, ',') }}"

      - name: Upload JSON Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: stock-${{ github.job }}-${{ strategy.job-index }}
          path: output/*.json

      - name: Upload Error Artifact
        uses: actions/upload-artifact@v4
        with:
          name: error-${{ github.job }}-${{ strategy.job-index }}
          path: error.log

  merge:
    needs: run-fetch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download All Chunks
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge Chunks
        run: |
          python stocks/merge_all_stocks.py --input-dir artifacts --output output/all.json

      - name: Upload JSON Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: stock-${{ github.job }}-${{ strategy.job-index }}
          path: output/*.json

  collect-and-push:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Push JSON to Target Repo
        if: success()
        env:
          TARGET_REPO_MAIN: ${{ secrets.TARGET_REPO }}
          TARGET_BRANCH_MAIN: ${{ secrets.TARGET_BRANCH }}
          TARGET_REPO_TEST: ${{ secrets.TARGET_REPO_TEST }}
          TARGET_BRANCH_TEST: ${{ secrets.TARGET_BRANCH_TEST }}
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          echo "🔍 Branch is $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            TARGET_REPO="$TARGET_REPO_MAIN"
            BRANCH="$TARGET_BRANCH_MAIN"
          elif [[ "$GITHUB_REF" == "refs/heads/test" ]]; then
            TARGET_REPO="$TARGET_REPO_TEST"
            BRANCH="$TARGET_BRANCH_TEST"
          else
            echo "🚫 Workflow not triggered on 'main' or 'test' branch. Exiting..."
            exit 0
          fi
          
          WORKDIR=$(mktemp -d)
          
          echo "📦 Cloning target repo..."
          git clone --depth 1 --branch $BRANCH https://x-access-token:${{ secrets.TARGET_REPO_PAT }}@$TARGET_REPO $WORKDIR
          
          echo "📂 Creating docs/tickers folder if missing..."
          mkdir -p $WORKDIR/docs/tickers
          
          echo "📂 Copying output files..."
          cp -f artifacts/**/all.json $WORKDIR/docs/tickers/
          
          cd $WORKDIR
          if git status --porcelain | grep .; then
            git add docs/tickers/all.json
            git commit -m "📈 Update all.json in docs/tickers/ from ${{ github.repository }} at ${{ github.run_id }}"
            git push origin $BRANCH
            echo "✅ JSON pushed to $TARGET_REPO docs/tickers/"
          else
            echo "ℹ️ No changes to commit."
          fi